![image](figs/fig-numpy.png)
# Introducción a NumPy



### - NumPy es una de las bibliotecas fundamentales en el ecosistema de Python para la ciencia de datos y la computación numérica. 

### - Proporciona soporte para arreglos multidimensionales y funciones matemáticas avanzadas.
### - La convierte en una herramienta esencial para el análisis de datos

### [https://numpy.org](https://numpy.org)
# <br>
# <br>
# <br>


## ¿Qué es NumPy?

### NumPy (Numerical Python) es una biblioteca de Python que ofrece:

###  - **Arreglos multidimensionales:** Estructuras de datos eficientes para almacenar y manipular grandes conjuntos de datos numéricos.

### - **Funciones matemáticas avanzadas:** Operaciones matemáticas y estadísticas que funcionan de manera eficiente en arreglos completos.

### - **Operaciones vectorizadas:** Cálculos rápidos sin necesidad de bucles explícitos, gracias a la implementación en C.

# <br>
# <br>
# <br>



# Contenido del Tutorial

###  1. **Instalación de NumPy**
  #### - Cómo instalar NumPy usando `pip` o `conda`.

### 2. **Conceptos Básicos de Arreglos**
   #### - Creación de arreglos con `np.array()`.
   #### - Indexación y segmentación de arreglos.
   #### - Tipos de datos y conversiones entre tipos.

### 3. **Operaciones Matemáticas y Estadísticas**
   #### - Operaciones aritméticas básicas: suma, resta, multiplicación y división.
   #### - Funciones estadísticas: media, mediana, desviación estándar.

### 4. **Manipulación de Arreglos**
   #### - Cambio de forma con `reshape()`.
   #### - Transposición y otras operaciones de reordenamiento.
   #### - Combinación y división de arreglos.

### 5. **Operaciones Avanzadas**
   #### - Uso de funciones de álgebra lineal: productos matriciales, determinantes y valores singulares.


# <br>
# <br>
# <br>

# 1. Instalación de NumPy

### - El único requisito previo para instalar NumPy es Python.

###  - NumPy se puede instalar con conda, con pip, con un gestor de paquetes en macOS y Linux, o desde el código fuente.

# <br>

## 1.1  Crear con conda el ambiente virtual incluyendo  python [El nombre del ambiente es "RNA" (Redes Neuronales Artificiales)]

```bash
conda create -n RNA python
```

### Activar el ambiente 

```bash
conda activate RNA
```

### Desactivar el ambiente

```bash
conda deactivate
```

# <br>


## 1.2  Instalar NumPy

### Usando el administrador de paquetes CONDA

```bash
conda install numpy

```

### Usando el administrador de paquetes PIP

```bash
pip install numpy
```


# <br>

## 2. Conceptos básicos de NumPy

### ¿Qué es una "matriz"?

#### - En programación, una matriz es una estructura para almacenar y recuperar datos. 

#### - A menudo hablamos de una matriz como si fuera una cuadrícula en el espacio, con cada celda almacenando un elemento de los datos. 

#### - Por ejemplo, si cada elemento de los datos fuera un número, podríamos visualizar una matriz “unidimensional” como una lista:


![image](./figs/fig-np-1d.png)


#### Una matriz bidimensional sería como una tabla:

![image](./figs/fig-np-2d.png)

#### - Una matriz tridimensional sería como un conjunto de tablas, tal vez apiladas como si estuvieran impresas en páginas separadas. 

#### - En NumPy, esta idea se generaliza a una cantidad arbitraria de dimensiones, la clase de matriz fundamental se llama ndarray: representa una "matriz N-dimensional".

#### - La mayoría de las matrices de NumPy tienen algunas restricciones. Por ejemplo:

   ####  + Todos los elementos de la matriz deben ser del mismo tipo de datos.

   ####  + Una vez creada, el tamaño total de la matriz no puede cambiar.

   ####  + La forma debe ser "rectangular", no "irregular"; Por ejemplo, cada fila de una matriz bidimensional debe tener la misma cantidad de columnas.

   ####  +  Cuando se cumplen estas condiciones, NumPy aprovecha estas características para hacer que la matriz sea más rápida, más eficiente en el uso de la memoria y más cómoda de usar que las estructuras de datos menos restrictivas.

#### En este contexto, se tilizaremos la palabra "matriz" para referirnos a una instancia de ndarray.


# <br>

# <br>

## 2.1 Fundamentos de las matrices
#### Fundamentos de las matrices


#### Una forma de inicializar una matriz es mediante una secuencia de Python, como una lista


#### Para empezar a utilizar el paquete se debe importar el paquete NumPy, es común usar el alias $np$

```python
import numpy as np
```


In [ ]:
import numpy as np

#Creación de un array de NumPy a partir de una lista proporcionada

a = np.array([1, 2, 3, 4, 5, 6])
print(a)

## Acceso a los elementos

-  ### Se puede acceder a los elementos de una matriz de varias maneras.

-  ### Por ejemplo, podemos acceder a un elemento individual de esta matriz como lo haríamos con un elemento de la lista original: utilizando el índice entero del elemento entre corchetes.
-  ### Se indexan desde la posición 0, similar a las listas de Python.

In [ ]:
# Extraer el valor del array en la posicón 0
print(f"a[0] = {a[0]}")

# Asignar el valor del array en la posicón 2
a[2] = 10

print("a[2] = {}".format(a[2]))

print(a)

In [ ]:
# Slices (Rebanadas de datos)

print(a[:3])

print(a[2:])


## Diferencia con slices
- ### Una diferencia importante es que la indexación de una lista mediante "slices"  copia los elementos en una nueva lista, pero la segmentación de una matriz devuelve una vista.

- ### La vista es un objeto que hace referencia a los datos de la matriz original. 
- ### La matriz original se puede modificar mediante la vista.

In [ ]:
# Se obtiene una slice de a, extrae los elementos de "a" a partir del índice 3 
# a =[ 1  2 10  4  5  6]

b = a[3:]

print(b)

# Se modifica la vista b (apunta a la dirección de memoria a)
b[0] = 40

# se imprime a que fue modificado a través de la vista b
print(a)

## Matrices de bidimensionales y de dimensiones superiores

- ### Se pueden inicializar matrices bidimensionales y de dimensiones superiores a partir de secuencias anidadas de Python.
 
- ### En NumPy, a la dimensión de una matriz se la denomina a veces “eje”. 
 
- ### Esta terminología puede resultar útil para distinguir entre la dimensionalidad de una matriz y la dimensionalidad de los datos representados por la matriz.
 
- ### Por ejemplo, la matriz "A"  podría representar tres puntos, cada uno de ellos dentro de un espacio de cuatro dimensiones, pero A tiene solo dos “ejes”.
 
- ### Otra diferencia entre una matriz y una lista de listas es que se puede acceder a un elemento de la matriz especificando el índice a lo largo de cada eje dentro de un único conjunto de corchetes, separados por comas. Por ejemplo, el elemento 8 está en la fila 1 y la columna 3: A[1,3]

In [ ]:
A = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8], 
              [9, 10, 11, 12]])
print(A)

In [ ]:
# Acceso a la matriz dentro del mismo corchete
print(A[1,3])

# De manera haitual en Python
print(A[1][3])


## 2.1.1  Attributos de Array

### ndim
- ### El número de dimensiones de una matriz está contenido en el atributo ndim.

In [ ]:
print(A.ndim)


## shape
- ### La forma de una matriz es una tupla de números enteros no negativos que especifican la cantidad de elementos a lo largo de cada dimensión.

In [ ]:
print(A.shape)
# matriz de 3 x 4 (renglones x columnas)


## size
 - ### El número total fijo de elementos de la matriz está contenido en el atributo de tamaño.

In [ ]:
print(A.size)
# matriz de 3 x 4 (12 elementos)


## dtype
- ### Las matrices suelen ser "homogéneas", lo que significa que contienen elementos de un solo "tipo de datos". El tipo de datos se registra en el atributo dtype.

In [ ]:
print(A.dtype)

# para especificar el tamaño del tipo de dato en la creación del array, float de 64 bits
B = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8], 
              [9, 10, 11, 12]], dtype=np.float64)
print(B.dtype)              


# <br>
# <br>


## 2.1.2 Tipos de datos y conversión

In [ ]:
import numpy as np

# Crear arreglos con diferentes tipos de datos

arr_int = np.array([1, 2, 3, 4], dtype=np.int32)  # Arreglo de enteros 32 bits
arr_float = np.array([1.1, 2.0, 3.0, 4.0], dtype=np.float64)  # Arreglo de flotantes 64 bits
arr_str = np.array(['A', '2', '3', '4'], dtype=np.str_)  # Arreglo de cadenas unicode

print("Arreglo de enteros:")
print(arr_int)
print("Tipo de dato:", arr_int.dtype)

print("\nArreglo de flotantes:")
print(arr_float)
print("Tipo de dato:", arr_float.dtype)

print("\nArreglo de cadenas:")
print(arr_str)
print("Tipo de dato:", arr_str.dtype)
            

In [ ]:

# Conversión de tipos de datos
arr_int_to_float = arr_int.astype(np.float64)  # Convertir enteros a flotantes
arr_float_to_int = arr_float.astype(np.int32)  # Convertir flotantes a enteros

print("\nArreglo de enteros convertido a flotantes:")
print(arr_int_to_float)
print("Tipo de dato:", arr_int_to_float.dtype)

print("\nArreglo de flotantes convertido a enteros:")
print(arr_float_to_int)
print("Tipo de dato:", arr_float_to_int.dtype)


## Otros métodos útiles

- Un objeto ndarray tiene muchos métodos que operan sobre la matriz o con ella de alguna manera, y que normalmente devuelven un resultado de matriz.

-  Estos métodos se explican brevemente a continuación. (para ver los detalles visitar la documentación de numpy [ver numpy.org](https://numpy.org/doc/stable/reference/arrays.ndarray.html#arrays-ndarray)).

| Método                | Descripción                                                       |
|-----------------------|-------------------------------------------------------------------|
| `numpy.zeros()`       | Crea un arreglo lleno de ceros con la forma especificada.         |
| `numpy.ones()`        | Crea un arreglo lleno de unos con la forma especificada.          |
| `numpy.empty()`       | Crea un arreglo sin inicializar con la forma especificada.        |
| `numpy.arange()`      | Crea un arreglo con valores igualmente espaciados en un rango especificado. |
| `numpy.linspace()`    | Crea un arreglo con un número específico de valores igualmente espaciados en un intervalo. |
| `numpy.reshape()`     | Cambia la forma de un arreglo sin cambiar sus datos.              |
| `numpy.flatten()`     | Devuelve una copia aplanada del arreglo en una dimensión.         |
| `numpy.transpose()`   | Devuelve el transpuesto del arreglo.                              |
| `numpy.sum()`         | Devuelve la suma de todos los elementos del arreglo o a lo largo de un eje especificado. |
| `numpy.mean()`        | Devuelve la media de los elementos del arreglo.                   |
| `numpy.std()`         | Devuelve la desviación estándar de los elementos del arreglo.     |
| `numpy.min()`         | Devuelve el valor mínimo de los elementos del arreglo.            |
| `numpy.max()`         | Devuelve el valor máximo de los elementos del arreglo.            |
| `numpy.argmin()`      | Devuelve el índice del valor mínimo en el arreglo.                |
| `numpy.argmax()`      | Devuelve el índice del valor máximo en el arreglo.                |
| `numpy.sort()`        | Devuelve una copia ordenada del arreglo.                          |
| `numpy.unique()`      | Devuelve los elementos únicos del arreglo.                        |
| `numpy.where()`       | Devuelve los elementos seleccionados de X o Y dependiendo de la condición|


### Ejemplos 

### np.ones

In [ ]:
#Creacion de matriz inicializada con 1s
np.ones((3,5))

### np.zeros

In [ ]:
#Creacion de matriz inicializada con 0s
np.zeros((3,5))

### np.eye

In [ ]:
#Creacion de matriz cuadrada con 1s en la diagonal

np.eye(5)

### np.arange

In [ ]:
# arange: crea un arreglo igualmente espaciado (inicio, parada, paso)
print(np.arange(0,15, 1))

print(np.arange(-10,10 + 1, 2))


### np.random.rand

In [ ]:
# rand: crea una muestra (muestras) de acuerdo a una distribución uniforme sobre  [0,1)
# crea una matriz de 3x4
a = np.random.rand(3,4)

print(a)



### np.random.randn

<img src="figs/fig-dnormal.png" width="30%">
<br>
<br>

<img src="figs/fig-dnormal_desv_estandard.png" width="30%" style="background-color: white;">

In [ ]:
# randn: crera una muestra (muestras) de acuerdo a la distribución estándar normal, media=0, varianza=1
# crea una matriz de 3x4
a = np.random.randn(3,4)

print(a)



### np.random.normal

In [ ]:
# normal: Extraer muestras aleatorias de una distribución normal (gaussiana).
# crea una lista con 10 elementos
mu, sigma = 0, 0.1 # media y desviación estándard
s = np.random.normal(mu, sigma, 10)
print(s)



In [ ]:
# normal: Extraer muestras aleatorias de una distribución normal (gaussiana).
# crea una matriz de 3x4
mu, sigma = 0, 0.1 # media y desviación estándard
s = np.random.normal(mu, sigma, size=(3,4))

print(s)


### np.random.randint

In [ ]:
import numpy as np
# randintn: Devuelve números enteros aleatorios desde un número inicial  (inclusive) hasta un valor final (exclusivo) de una distribución uniforme discreta.
#  np.random.randint(inicial, final, size=xxx)

a = np.random.randint(-10,10)
print(a)

# Devuelve un número entre 1 y 10 
a = np.random.randint(1,10)
print(a)

# Devuelve un vector número entre 1 y 20 
a = np.random.randint(1,20, size=10)
print(a)

# Crea una matriz de 3x4
a = np.random.randint(1,10, size=(3,4))
print(a)


### np.linspace

In [ ]:
# linspace: Devuelve el número de muestras espaciadas uniformemente, calculadas sobre el intervalo [inicio, fin] dependiendo del valor endpoint=True (default) incluye al valor "fin".
# 
import numpy as np
x = np.linspace(0, 10, 30)  # 30 puntos entre 0 y 10
print(x)


### np.ones_like

In [ ]:
# ones_like: Devuelve una matriz de unos con la misma forma y tipo que una matriz dada.

# Crea una matriz de 3x4
y = np.random.normal(mu, sigma, size=(3,4))
print(y)
b = np.ones_like(y)
print(b)


### np.reshape

In [ ]:
# Cambia la forma de un arreglo sin cambiar sus datos

A = np.arange(0,15)
print("A =",  A)
print(A.shape)

A = A.reshape(3,5)
print("forma nueva A = ")
print(A)
print(A.shape)


### np.full

In [ ]:
# Crea un matriz con valores inicializados a un valor específico ( matriz, valor)

np.full((3, 4), 8)


### np.insert

In [ ]:
# Insertar valores a lo largo del eje dado antes de los índices dados.

a = np.array([1, 2, 3, 4])

# inserta el valor 5 en el índice 1
print(np.insert(a, 1, 5))

# inserta el arreglo a partir del índice 1, mueve los demás elementos
print(np.insert(a, 1, [5, 6, 7, 8]))


### np.flatten

In [ ]:
# Devuelve una copia de la matriz colapsada en una dimensión.

a = np.array([[1, 1], [2, 2], [3, 3]])
print(a.flatten())


### np.where
### np.where(condition, [x, y ])

In [ ]:
# Devuelve elementos elegidos entre x o y dependiendo de la condición.

import numpy as np
a = np.arange(10)
print(a)
r = np.where(a < 5, a, 10*a)

print(r)


[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 50 60 70 80 90]


In [111]:
a = np.array([[1, 5, 2],
              [3, 2, 4],
              [8, 3, 6]])
r = np.where(a < 4, a, 0)  
print(r)

[[1 0 2]
 [3 2 0]
 [0 3 0]]


## Ejemplo de graficación con matplotlib
- ### `plot`: se utiliza comúnmente para crear gráficos de líneas que conectan puntos de datos, lo que es ideal para mostrar cómo cambian los datos en relación con otra variable, como el tiempo.
- ### `bar`: se utiliza para crear gráficos de barras.

- ### [https://matplotlib.org](https://matplotlib.org)


In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Datos para el gráfico
x = np.linspace(0, 10, 100)  # 100 puntos entre 0 y 10
y1 = np.sin(x)               # Función seno
y2 = np.cos(x)               # Función coseno

# Crear una nueva figura
plt.figure(figsize=(10, 6))

# Graficar la función seno
# datos tabulares para el eje x =x; eje y = y1

plt.plot(x, y1, label='Seno', color='orange', linestyle=':', linewidth=2)

# Graficar la función coseno

plt.plot(x, y2, label='Coseno', color='green', linestyle='-', linewidth=2)

# Añadir título y etiquetas
plt.title('Funciones Seno y Coseno')
plt.xlabel('Eje X')
plt.ylabel('Eje Y')

# Añadir leyendas
plt.legend()

# Mostrar el gráfico
plt.grid(True)
plt.show()

## Ejemplo. Gráfico de barras
### la función `bar` se utiliza para crear gráficos de barras. Los gráficos de barras son útiles para visualizar datos categóricos o discretos, permitiendo comparar fácilmente diferentes categorías en términos de una variable cuantitativa.

In [ ]:
import matplotlib.pyplot as plt


# Datos de ejemplo
materias = ['Matemáticas', 'Ciencia', 'Historia', 'Lengua', 'Arte']
calificaciones = [85, 90, 78, 88, 95]

# Crear el gráfico de barras
plt.figure(figsize=(10, 6))
plt.bar(materias, calificaciones, color='skyblue', edgecolor='black')

# Añadir título y etiquetas
plt.title('Calificaciones del Estudiante')
plt.xlabel('Materias')
plt.ylabel('Calificaciones')

# Mostrar el gráfico
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.show()


## Histogramas

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Generar arreglo
arreglo = np.random.randn(1000)

# Crear histograma  bins= tamaño del espaciado de los datos
plt.hist(arreglo, bins=5, edgecolor='black')
plt.title("Histograma de datos generados con randn")
plt.xlabel("Valor")
plt.ylabel("Frecuencia")
plt.show()

# Ejercicios

## 1. **Crear Matrices**:
   - ### Crea una matriz $ 3 \times 3 $ con valores enteros del 1 al 9.
   - ### Crea una matriz diagonal de $ 4 \times 4 $ con valores 1 en la diagonal principal y 0 en el resto.

## 2. **Extraer Submatrices y Cambiar Forma**: 
   - ### Extrae una submatriz de $ 2 \times 2 $  de una matriz $ 4 \times 4 $.
   - ### Cambia la forma de una matriz $ 6 \times 2 $ a una matriz $ 3 \times 4 $ que mantiene los elementos.


## 3. **Graficación con matplotlib**: 
   - ### 3.1 Crear un conjunto de datos para un intervalo indicado (por ejemplo, -10 a 10) y aplicarlo para graficar las siguientes funciones:
      - ### a) $ f(x) = 3x^4 - 5x^2 + 2x - 7 $
      - ### b) Calcular la derivada de $ f'(x) $      
      - ### c) Graficar la función $f(x)$ y su derivada $f'(x)$ en una misma gráfica

   - ### Crear un conjunto de datos para un intervalo indicado (por ejemplo, -5 a 5) y aplicarlo para graficar las siguientes funciones:
      - ### a) $ f(x) =  e^{-3x^2}  $
      - ### b) Calcular la derivada de $ f'(x) $      
      - ### c) Graficar la función $f(x)$ y su derivada $f'(x)$ en una misma gráfica
   


 # </br>
 # </br>

##  3. **Operaciones Matemáticas y Estadísticas**

In [ ]:
import numpy as np

# Crear arreglos
A = np.array([1, 2, 3, 4])
B = np.array([5, 6, 7, 8])


# Operaciones elementales
print("Arreglo  A:", A)
print("Arreglo B:", B)

# Suma y resta
suma = A + B
resta = A - B

print("\nSuma de A+B:")
print(suma)

print("\nResta de A-B :")
print(resta)


In [ ]:

# Multiplicación y división (elemento a elemento)

multiplicacion = A * B
division = A / B

print("\nMultiplicación de arreglos:")
print(multiplicacion)

print("\nDivisión de arreglos:")
print(division)


### Operaciones avanzadas

In [ ]:
# Operaciones matemáticas

print("\nOperaciones matemáticas avanzadas:")

# Potencia
C = np.power(A, 2)  # Eleva cada elemento de A al cuadrado
print("Potencia (A^2):")
print(C)

In [ ]:

# Raíz cuadrada

D = np.sqrt(B)  # Calcula la raíz cuadrada de cada elemento de B
print("Raíz cuadrada de B:")
print(D)



In [ ]:

# Estadísticas
print("\nEstadísticas:")

# Media y desviación estándar
media = np.mean(A)
desviacion_estandar = np.std(A)

print("Media de A:")
print(media)


In [ ]:

print("Desviación estándar de A:")
print(desviacion_estandar)


In [ ]:

# Máximo y mínimo

maximo = np.max(B)
minimo = np.min(B)

print("\nValor máximo de B:")
print(maximo)

print("Valor mínimo de B:")
print(minimo)


In [ ]:

# Producto escalar
producto_escalar = np.dot(A, B)
print("\nProducto escalar de A y B:")
print(producto_escalar)

# Ejercicios


### 1. **Generación y graficación de datos**:
   - ###  Simular temperaturas corporales (5000 elementos medidos) con una distribución normal. 
      -  ### `temperaturas = np.random.normal(36.5, 0.5, 5000)` 
   - ### Calcular y mostrar la media, la mediana y la desviación estándar de los datos. 
   - ### Graficar el histograma

### 2. **Generación y graficación de datos**:
   - ### Genera un arreglo aleatorio de 5000 elementos que representan las ventas mensuales de una empresa. Proporcionar la menor venta mensual, así como la mayor venta mensual.
   - ### Calcular y mostrar la media, la mediana y la desviación estándar del arreglo.
   - ### Generar el histograma

### 3. **Generación y graficación de datos**:
   - ### Genera un arreglo de 5000 elementos de enteros aleatorios que representan calificaciones entre 0 y 100 de un grupo de 5000 estudiantes. 
   - ### Calcular y mostrar la media, la mediana y la desviación estándar del arreglo.
   - ### Generar el histograma