![image](figs/fig-numpy.png)
# Introducción a NumPy (...Continuación)



### - NumPy es una de las bibliotecas fundamentales en el ecosistema de Python para la ciencia de datos y la computación numérica. 

### - Proporciona soporte para arreglos multidimensionales y funciones matemáticas avanzadas.
### - La convierte en una herramienta esencial para el análisis de datos

### [https://numpy.org](https://numpy.org)


# <br>
# <br>
# <br>


## ¿Qué es NumPy?

### NumPy (Numerical Python) es una biblioteca de Python que ofrece:

###  - **Arreglos multidimensionales:** Estructuras de datos eficientes para almacenar y manipular grandes conjuntos de datos numéricos.

### - **Funciones matemáticas avanzadas:** Operaciones matemáticas y estadísticas que funcionan de manera eficiente en arreglos completos.

### - **Operaciones vectorizadas:** Cálculos rápidos sin necesidad de bucles explícitos, gracias a la implementación en C.

# <br>
# <br>
# <br>



# Contenido del Tutorial

###  1. **Instalación de NumPy**
  #### - Cómo instalar NumPy usando `pip` o `conda`.

### 2. **Conceptos Básicos de Arreglos**
   #### - Creación de arreglos con `np.array()`.
   #### - Indexación y segmentación de arreglos.
   #### - Tipos de datos y conversiones entre tipos.

### 3. **Operaciones Matemáticas y Estadísticas**
   #### - Operaciones aritméticas básicas: suma, resta, multiplicación y división.
   #### - Funciones estadísticas: media, mediana, desviación estándar.

### 4. **Manipulación de Arreglos**
   #### - Cambio de forma con `reshape()`.
   #### - Transposición y otras operaciones de reordenamiento.
   #### - Combinación y división de arreglos.

### 5. **Operaciones Avanzadas**
   #### - Uso de funciones de álgebra lineal: productos matriciales, determinantes y valores singulares.


# <br>
# <br>
# <br>

# Broadcasting 
- ### El término broadcasting describe cómo NumPy trata las matrices con diferentes formas durante las operaciones aritméticas. 
- ### Sujeto a ciertas restricciones, la matriz más pequeña se "transmite" a través de la matriz más grande para que tengan formas compatibles.

- ### Las operaciones de NumPy se realizan normalmente en pares de matrices, elemento por elemento. En el caso más simple, las dos matrices deben tener exactamente la misma forma.

- ### Al operar sobre dos matrices, NumPy compara sus formas elemento por elemento. Comienza con la dimensión final (es decir, la más a la derecha) y avanza hacia la izquierda. 
    - ### <span style="color:red;">Dos dimensiones son compatibles cuando: son iguales o una de ellas es de dimensión 1.</span> 

- ### Las matrices de entrada no necesitan tener la misma cantidad de dimensiones. 
- ### <span style="color:red;">La matriz resultante tendrá la misma cantidad de dimensiones que la matriz de entrada con la mayor cantidad de dimensiones</span>, donde el tamaño de cada dimensión es el tamaño más grande de la dimensión correspondiente entre las matrices de entrada. 
- ### Considere que se supone que las dimensiones faltantes tienen un tamaño de uno.


- ### En numpy, la instrucción A * B calcula la multiplicación elemento por elemento de las matrices o tensores A y B. 
    - ### <span style="color:red;">Si las matrices tienen formas diferentes, se convertirán automáticamente para que tengan formas compatibles</span> __replicando implícitamente ciertas dimensiones__; esto <span style="color:red;"> se denomina broadcasting</span> . Las siguientes reglas de conversión se aplican en orden:

        - #### 1. Si las dos matrices difieren en su número de dimensiones, la forma de la matriz que tiene menos dimensiones se rellena con dimensiones 1 en el lado izquierdo. Por ejemplo, un escalar se convertirá en un vector shape=(1,) y un vector en una matriz con una fila shape=(1,N).
        - #### 2. Si la forma de las dos matrices no coincide en ninguna dimensión, la matriz con forma igual a 1 en esa dimensión se estira para que coincida con la otra forma, replicando el contenido correspondiente.
        - #### 3. Si en alguna dimensión los tamaños no coinciden y ninguno es igual a 1, se genera un error.


## Ejemplo 1
![image](./figs/fig-broadcasting1.png)

- Una matriz unidimensional (b) agregada a una matriz bidimensional (a) da como resultado un "broadcasting" si el número de elementos de la matriz unidimensional coincide con el número de columnas de la matriz bidimensional.

In [ ]:
import numpy as np

a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])

b = np.array([1.0, 2.0, 3.0])

print(f'a=\n{a}\n')
print(f'a.shape=\n{a.shape}\n')

print(f'b=\n{b}\n')
print(f'b.shape=\n{b.shape}\n')

print(f'a+b=\n{a+b}\n')



## Ejemplo 2
![image](./figs/fig-broadcasting2.png)


In [ ]:
import numpy as np

a = np.array([[ 0.],
              [10.],
              [20.],
              [30.]])

b = np.array([1.0, 2.0, 3.0])

print(f'a=\n{a}\n')
print(f'a.shape=\n{a.shape}\n')

print(f'b=\n{b}\n')
print(f'b.shape=\n{b.shape}\n')

print(f'a+b=\n{a+b}\n')



# Expandir dimensiones
- ## $np.expand\_dims$: Inserta un nuevo eje que aparecerá en la posición del eje en la forma de la matriz expandida.
- ## Útil para hacer broadcasting

## Vector fila, se agrega mediante axis=0

In [ ]:
a = np.array([1, 2, 3])

print(f'a=\n{a}\n')
print(f'a.shape=\n{a.shape}\n')

# agregar dimensión al vector a, lo convierte en vector fila
b = np.expand_dims(a, axis=0)

print(f'b=\n{b}\n')
print(f'b.shape=\n{b.shape}\n')


### Forma equivalente con $np.newaxis$ equivalente a agregar $None$ en el eje de las filas

In [ ]:

# teniendo "a" como vector se puede agregar una dimensión adicional con np.newaxis es equivalente a gregar None 

a = np.array([0, 10, 20, 30])

print(f'a=\n{a}\n')

b = a[np.newaxis, :] # agrega una dimension en el eje de las filas

print(f'b=\n{b}\n')
print(f'b.shape=\n{b.shape}\n')

c = a[None, :] # agrega una dimension en el eje de las filas

print(f'c=\n{c}\n')
print(f'c.shape=\n{c.shape}\n')

## Vector columna, se agrega mediante axis=1

In [ ]:
a = np.array([1, 2, 3])

print(f'a=\n{a}\n')
print(f'a.shape=\n{a.shape}\n')

# # agregar dimensión al vector a, lo convierte en vector columna 
b = np.expand_dims(a, axis=1)

print(f'b=\n{b}\n')
print(f'b.shape=\n{b.shape}\n')


### Forma equivalente con $np.newaxis$ equivalente a agregar $None$ en el eje de las columnas

In [ ]:

# teniendo "a" como vector se puede agregar una dimensión adicional con np.newaxis es equivalente a gregar None 

a = np.array([0, 10, 20, 30])

print(f'a=\n{a}\n')

b = a[:, np.newaxis] # agrega una dimension en el eje de las columnas

print(f'b=\n{b}\n')
print(f'b.shape=\n{b.shape}\n')

c = a[:, None] # agrega una dimension en el eje de las columnas

print(f'c=\n{c}\n')
print(f'c.shape=\n{c.shape}\n')




### Formas equivalentes reshape: comodín -1  (ajusta los elementos para completar la forma adecuada, usar solo una dimensión no conocida) 

In [ ]:
# teniendo "a" como vector se puede agregar una dimensión adicional con np.newaxis es equivalente a usar reshape

a = np.array([0, 10, 20, 30])

print(f'a=\n{a}\n')

b = a[np.newaxis, :] # agrega una dimension en el eje de las filas

print(f'b=\n{b}\n')
print(f'b.shape=\n{b.shape}\n')

c = a.reshape(-1, 4) # agrega una dimension en el eje de las filas

print(f'c=\n{c}\n')
print(f'c.shape=\n{c.shape}\n')

In [ ]:
# teniendo "a" como vector se puede agregar una dimensión adicional con np.newaxis es equivalente a usar reshape

a = np.array([0, 10, 20, 30])

print(f'a=\n{a}\n')

b = a[:, np.newaxis] # agrega una dimension en el eje de las columnas

print(f'b=\n{b}\n')
print(f'b.shape=\n{b.shape}\n')

c = a.reshape(4, -1) # agrega una dimension en el eje de las filas

print(f'c=\n{c}\n')
print(f'c.shape=\n{c.shape}\n')


In [ ]:
a = np.array([[1, 2],
              [3, 4]])


b = np.array([[5, 6, 7],
              [8, 9, 10]])

c = a[np.newaxis,:].reshape()
c+b

# $np.squeeze$ Remover ejes (dimesión) de longitud 1 de la matriz.

In [17]:
a = np.array([[[0], [1], [2]]])

print(f"a=\n{a}\n")
print(f"a.shape=\n{a.shape}\n")

b = np.squeeze(a)

print(f"b=\n{b}\n")
print(f"b.shape=\n{b.shape}\n")


a=
[[[0]
  [1]
  [2]]]

a.shape=
(1, 3, 1)

b=
[0 1 2]

b.shape=
(3,)



In [18]:
# Eliminar eje 0
a = np.array([[[0], [1], [2]]])

print(f"a=\n{a}\n")
print(f"a.shape=\n{a.shape}\n")

b = np.squeeze(a, axis=0)

print(f"b=\n{b}\n")
print(f"b.shape=\n{b.shape}\n")


a=
[[[0]
  [1]
  [2]]]

a.shape=
(1, 3, 1)

b=
[[0]
 [1]
 [2]]

b.shape=
(3, 1)



In [19]:
# Eliminar eje 2
a = np.array([[[0], [1], [2]]])

print(f"a=\n{a}\n")
print(f"a.shape=\n{a.shape}\n")

b = np.squeeze(a, axis=2)

print(f"b=\n{b}\n")
print(f"b.shape=\n{b.shape}\n")


a=
[[[0]
  [1]
  [2]]]

a.shape=
(1, 3, 1)

b=
[[0 1 2]]

b.shape=
(1, 3)



# Ejercicios

## Dada la siguiente: matriz score_matrix Realizar las operaciones que se indican

```Python
# Definir un conjunto de datos de ventas (4 tiendas x 3 meses)
sales_data = np.array([
    [200000, 220000, 250000],  # Ventas de la tienda 1
    [150000, 180000, 210000],  # Ventas de la tienda 2
    [300000, 320000, 350000],  # Ventas de la tienda 3
    [400000, 420000, 430000]   # Ventas de la tienda 4
])

```

- ### Normalizar los datos de acuerdo al mes por medio de las matrices y vectores correspondientes:
   - ### dato\_normalizado =  (datos de ventas  - media de ventas) / desviación estandar de las ventas
   - ### Mostrar la media por mes
   - ### Mostrar la desviación estándar por mes
   - ### Mostrar los datos normalizados




## Ejercicios Broadcasting

# Ejercicio1. 

### Dada la siguientes definiciones para A y v, explicar ¿Qué pasos sigue NumPy para realizar esta suma y cómo afecta el resultado final?"

```Python
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

v = np.array([1, 0, -1])

B = A + v

```



## Ejercicio2. 

### Dada la siguientes definiciones para A y v, explicar ¿Qué pasos sigue NumPy para realizar esta suma y cómo afecta el resultado final?"


```Python
import numpy as np

# Crear una matriz 3x3
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])


v = np.array([[1],
              [2],
              [3]])


B = A * v

print(B)

```

## Ejercicio3. 

### Dada la siguientes definiciones para A y v, explicar ¿Qué pasos sigue NumPy para realizar esta suma y cómo afecta el resultado final?"

```Python
import numpy as np

# Crear una matriz 3x3
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Sumar un escalar a la matriz
c = 10
B = A + c

print(B)

```

## Ejercicio4. 

### Dada la siguientes definiciones para A y v, explicar ¿Qué pasos sigue NumPy para realizar esta suma y cómo afecta el resultado final?"

```Python
import numpy as np

# Crear un vector de longitud 3
v = np.array([1, 2, 3])

# Crear una matriz 2x3
A = np.array([[4, 5, 6],
              [7, 8, 9]])

# Multiplicar el vector por la matriz
B = v * A

print(B)
```

## Ejercicio5. 

### Dada la siguientes definiciones para A y v, explicar ¿Qué pasos sigue NumPy para realizar esta suma y cómo afecta el resultado final?"

```Python
import numpy as np

# Crear una matriz 4x3
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])


mean1 = A.mean(axis=0)
print(mean1)

mean2 = A.mean(axis=0, keepdims=True)
print(mean2)


mean3 = A.mean(axis=1)
print(mean3)

mean4 = A.mean(axis=1, keepdims=True)
print(mean4)

```

## Ejercicio6. 

## En este ejemplo de normalización de filas presentado, explica cómo se realiza el broadcasting para restar la media y dividir por la desviación estándar en cada fila de la matriz. Detalla cómo NumPy ajusta las dimensiones de los arreglos mean y std para permitir estas operaciones. Si es el caso, indicar cómo se expanden las dimensiones y replican los datos.

```Python
import numpy as np
# Crear una matriz 4x3
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])

# Calcular la media 
mean = A.mean(axis=1, keepdims=True)

# Calcular la desviación estándar
std = A.std(axis=1, keepdims=True)

# Normalizar  (restar la media y dividir por la desviación estándar)
B = (A - mean) / std

print(B)

```

# Ejercicio7

### En el ejemplo de cálculo de la distancia euclidiana, explica cómo se utiliza el broadcasting para restar el reference_point de todos los puntos en la matriz points. Además, describe cómo se aplica el broadcasting en la operación de elevación al cuadrado y la suma de los componentes para calcular la distancia.

### - Práctica: Adicionalmente, después de realizar la actividad anterior, modificar el programa para que el resultado mantenga la forma de la matriz original. 



### La ecuación de la distancia euclidiana entre dos puntos $ A = (x_1, y_1) $ y $ B = (x_2, y_2) $ en un espacio 2D es:


</br>

$
\Large d(A, B) = \sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}
$

</br>


```Python
import numpy as np

# Crear una matriz 5x2 donde cada fila es un punto (x, y) en 2D
points = np.array([[1, 2],
                   [3, 4],
                   [5, 6],
                   [7, 8],
                   [9, 10]])

# Definir un punto de referencia en 2D
reference_point = np.array([4, 5])

# Calcular la distancia euclidiana entre cada punto y el punto de referencia
distances = np.sqrt(np.sum((points - reference_point) ** 2, axis=1))

print(distances)

```

# Representación de datos $X$, pesos $W$,  sesgos $B$ ($bias$) y neuronas en el contexto de redes neuronales

<img src="figs/fig-repr_red_neuronal.png" width="500">


## En las siguientes representaciones, 
 - ### $X$ : representa un conjunto de datos;  cada fila es un ejemplo y cada elemento (columna) representan una característica de los datos de entrenamiento, por ejemplo $x_{11}$
$$
\mathbf{X} = \begin{bmatrix}
x_{11} & x_{12} & \cdots & x_{1n} \\
x_{21} & x_{22} & \cdots & x_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
x_{m1} & x_{m2} & \cdots & x_{mn} \\
\end{bmatrix} \in \mathbb{R}^{m \times n}

$$

 - ### $W$ : representa un conjunto de neuronas; cada fila es una reurona y cada cada elemento (columna) representan un peso $w_{ik}$; neurona $i$; característica $k$
 - ### La neurona $N_1$ esta definida por la fila 1: 
    $$ N_1 = \begin{bmatrix}w_{11} & w_{12} & \cdots & w_{1n}\end{bmatrix}$$




$$
\mathbf{W} = \begin{bmatrix}
w_{11} & w_{12} & \cdots & w_{1n} \\
w_{21} & w_{22} & \cdots & w_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
w_{m1} & w_{m2} & \cdots & w_{mn} \\
\end{bmatrix} \in \mathbb{R}^{m \times n}
$$


### La salida de cada neurona para la imagen del ejemplo se calcularía de la siguiente forma:


$$
    \mathbf{Z} =  \mathbf{X} \cdot\mathbf{W}^\top + \mathbf{B} = 
    \begin{bmatrix}
    x_1 & x_2 & x_3 & x_4 
    \end{bmatrix}
    \cdot
    \begin{bmatrix}
    w_{11} & w_{21} \\
    w_{12} & w_{22} \\
    w_{13} & w_{23} \\
    w_{14} & w_{24}
    \end{bmatrix}
    
    +
    \begin{bmatrix}
    b_1 & b_2 
    \end{bmatrix}
$$





# Ejercicio

## Para los siguientes datos, calcular la operación de cada neurona.
## Ejercicio1: 
- ### Hacer el cálculo para una capa de una red neuronal con el siguiente ejemplo de entrenamiento que contiene 10 características
- ### Definir la matriz de neuronas-pesos $W$ con 2 neuronas, inicializarla de forma aleatoria
- ### Definir el vector de sesgos $B$ inicializarlo de manera aleatoria

$$ 
\mathbf{X} = \begin{bmatrix}
1.2 & 0.5 & -0.8 & 2.1 & -1.5 & 0.3 & 1.8 & -0.2 & 0.9 & 1.1 \\
\end{bmatrix} \in \mathbb{R}^{1 \times 10}
$$

</br>
</br>
</br>

## Ejercicio2: 
- ### Hacer el cálculo para una capa de una red neuronal con el siguiente conjunto  de entrenamiento (3 ejemplos) que contiene 10 características
- ### Definir la matriz de neuronas-pesos $W$ con 2 neuronas, inicializarla de forma aleatoria
- ### Definir el vector de sesgos $B$ inicializarlo de manera aleatoria


$$ 
\mathbf{X} = \begin{bmatrix}
1.2 & 0.5 & -0.8 & 2.1 & -1.5 & 0.3 & 1.8 & -0.2 & 0.9 & 1.1 \\
0.8 & 1.2 & -0.3 & 1.5 & -0.8 & 0.6 & 2.1 & 0.1 & 1.2 & 0.7 \\
-0.5 & 1.8 & 0.2 & 0.9 & -1.2 & 1.1 & 0.4 & -0.3 & 0.8 & 1.5 \\
\end{bmatrix} \in \mathbb{R}^{3 \times 10}
$$
